# Generated by Django 4.2 on 2023-04-30 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_userapp_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userapp',
            name='date_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userapp',
            name='phone',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
