# Generated by Django 4.2 on 2023-04-30 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_userapp_date_birth_alter_userapp_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='userapp',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userapp',
            name='is_manager',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userapp',
            name='is_searcher',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userapp',
            name='is_student',
            field=models.BooleanField(default=True),
        ),
    ]
